
spring: {}
server:
  port: "8080"
application:
  name: "CURD operation"
level: {}
org: {}
datasource:
  password: "Your Password"
  driver-class-name: "com.mysql.cj.jdbc.Driver"
  url: "jdbc:mysql://localhost:3306/curd_test"
  username: "root"
logging: {}
jpa:
  show-sql: "true"
springframework:
  web: "DEBUG"
hibernate:
  ddl-auto: "update"
